plugins:
    path:     /
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:index" }

plugins_show:
    path:     /{id}/show
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:show" }

plugins_delete:
    path:     /{id}/delete
    defaults: { _controller: "LOCKSSOMaticCRUDBundle:Plugins:delete" }
    requirements: { _method: post|delete }
