locksso_matic_logging:
    resource: "@LOCKSSOMaticLoggingBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_plugin:
    resource: "@LOCKSSOMaticPluginBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_core:
    resource: "@LOCKSSOMaticCoreBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_pln_monitor:
    resource: "@LOCKSSOMaticPLNMonitorBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_crud:
    resource: "@LOCKSSOMaticCRUDBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_sword:
    resource: "@LOCKSSOMaticSWORDBundle/Resources/config/routing.yml"
    prefix:   /

locksso_matic_pln_importer:
    resource: "@LOCKSSOMaticPLNImporterBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

locksso_matic_user:
    resource: "@LOCKSSOMaticUserBundle/Resources/config/routing.yml"
    prefix: /
    