security:
    
    acl:
        connection: default
        
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_LOMADMIN: ROLE_USER
        ROLE_ADMIN: ROLE_LOMADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        login:
            pattern: ^/(login$|resetting)
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       
                path:   fos_user_security_logout
            anonymous:    false
            switch_user:  { role: ROLE_ADMIN }
            remember_me:
                key: "%secret%"
                # one year, in seconds.
                lifetime: 31536000 
                path: /
                # defaults to current domain from $_SERVER
                domain: ~
        
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
