services:
    locksso_matic_default.example:
        class: LOCKSSOMatic\DefaultBundle\Twig\PlnsExtension
        arguments: [@doctrine, @session]
        tags:
            - { name: twig.extension }
